domain: mir-server.io

image: prod-comms.docker-registry.canonical.com/mir-server.io

env:
  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: ubuntu-api-key
      name: discourse-api
    
  - name: SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

extraHosts:
  - domain: mirserver.io
    useParentTLS: True

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'mir-server.io' ) {
      rewrite ^ https://mir-server.io$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
